version: "3.9"

services:
  web:
    build: .
    container_name: kpimanager_api
    ports:
      - "8081:8002"
    environment:
      - DATABASE_URL=postgresql://admeiasa:eiasa.adm2024@db:5432/etbkpi_manager
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: etbkpi_manager
    environment:
      - POSTGRES_USER=admeiasa
      - POSTGRES_PASSWORD=eiasa.adm2024
      - POSTGRES_DB=etbkpi_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  postgres_data:
